name: Docs

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Setup docfx
        run: dotnet tool update -g docfx

      - name: Build documentation
        run: docfx ./docfx/docfx.json

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docfx/_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
